//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuvoControl.Client.WcfTestConsole.NuvoControlReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NuvoControlReference.INuvoControl")]
    public interface INuvoControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INuvoControl/StartSession", ReplyAction="http://tempuri.org/INuvoControl/StartSessionResponse")]
        bool StartSession(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INuvoControl/EndSession", ReplyAction="http://tempuri.org/INuvoControl/EndSessionResponse")]
        bool EndSession(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INuvoControl/IConfigureIfc", ReplyAction="http://tempuri.org/INuvoControl/IConfigureIfcResponse")]
        object IConfigureIfc();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface INuvoControlChannel : NuvoControl.Client.WcfTestConsole.NuvoControlReference.INuvoControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class NuvoControlClient : System.ServiceModel.ClientBase<NuvoControl.Client.WcfTestConsole.NuvoControlReference.INuvoControl>, NuvoControl.Client.WcfTestConsole.NuvoControlReference.INuvoControl {
        
        public NuvoControlClient() {
        }
        
        public NuvoControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NuvoControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NuvoControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NuvoControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool StartSession(System.Guid clientId) {
            return base.Channel.StartSession(clientId);
        }
        
        public bool EndSession(System.Guid clientId) {
            return base.Channel.EndSession(clientId);
        }
        
        public object IConfigureIfc() {
            return base.Channel.IConfigureIfc();
        }
    }
}
